/**
 * This function is generated by RT-LAB during model compilation (at 'generation' step).
 * This function copies data from src to dst, ignoring pointers.
 * Note that only PWork are supposed to be pointers within a DWork structure
 * and that sub-structures are copied in one operation since they do not contain pointers.
 */
int OpalSnapshot_Copy_DWork(void * src, void * dst) {
   D_Work * pSrc = (D_Work*)src;
   D_Work * pDst = (D_Work*)dst;
   int size = 0, eltSize = 0;

   eltSize = sizeof(pSrc->SFunction_PreviousInput);
   memcpy(&pDst->SFunction_PreviousInput, &pSrc->SFunction_PreviousInput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->NextOutput);
   memcpy(&pDst->NextOutput, &pSrc->NextOutput, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->NextOutput_j);
   memcpy(&pDst->NextOutput_j, &pSrc->NextOutput_j, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->NextOutput_k);
   memcpy(&pDst->NextOutput_k, &pSrc->NextOutput_k, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->NextOutput_i);
   memcpy(&pDst->NextOutput_i, &pSrc->NextOutput_i, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->NextOutput_a);
   memcpy(&pDst->NextOutput_a, &pSrc->NextOutput_a, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->NextOutput_c);
   memcpy(&pDst->NextOutput_c, &pSrc->NextOutput_c, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->NextOutput_a1);
   memcpy(&pDst->NextOutput_a1, &pSrc->NextOutput_a1, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->NextOutput_cx);
   memcpy(&pDst->NextOutput_cx, &pSrc->NextOutput_cx, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->NextOutput_h);
   memcpy(&pDst->NextOutput_h, &pSrc->NextOutput_h, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->NextOutput_k1);
   memcpy(&pDst->NextOutput_k1, &pSrc->NextOutput_k1, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RandSeed);
   memcpy(&pDst->RandSeed, &pSrc->RandSeed, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RandSeed_b);
   memcpy(&pDst->RandSeed_b, &pSrc->RandSeed_b, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RandSeed_l);
   memcpy(&pDst->RandSeed_l, &pSrc->RandSeed_l, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RandSeed_p);
   memcpy(&pDst->RandSeed_p, &pSrc->RandSeed_p, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RandSeed_h);
   memcpy(&pDst->RandSeed_h, &pSrc->RandSeed_h, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RandSeed_n);
   memcpy(&pDst->RandSeed_n, &pSrc->RandSeed_n, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RandSeed_i);
   memcpy(&pDst->RandSeed_i, &pSrc->RandSeed_i, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RandSeed_nt);
   memcpy(&pDst->RandSeed_nt, &pSrc->RandSeed_nt, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RandSeed_a);
   memcpy(&pDst->RandSeed_a, &pSrc->RandSeed_a, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->RandSeed_m);
   memcpy(&pDst->RandSeed_m, &pSrc->RandSeed_m, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->SFunction_IWORK);
   memcpy(&pDst->SFunction_IWORK, &pSrc->SFunction_IWORK, eltSize);
   size += eltSize;

   return size;
}

/**
 * This function is generated by RT-LAB during model compilation (at 'generation' step).
 * This function copies data from a raw buffer (src) 
 * to an RT_MODEL structure(dst), ignoring pointers.
 * Note that sub-structures are copied in one operation since they cannot contain pointers.
 */
int OpalSnapshot_Copy_TimingData(void * src, void * dst) {
   RT_MODEL	tmpBuffer;
   RT_MODEL * pSrc = &tmpBuffer;
   RT_MODEL * pDst = (RT_MODEL *)dst;
   int TimingSize = sizeof(tmpBuffer.Timing);
   int size = 0, eltSize = 0;

   memcpy(&tmpBuffer.Timing, src, TimingSize);

   eltSize = sizeof(pSrc->Timing.clockTick0);
   memcpy(&pDst->Timing.clockTick0, &pSrc->Timing.clockTick0, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.clockTick1);
   memcpy(&pDst->Timing.clockTick1, &pSrc->Timing.clockTick1, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.clockTickH0);
   memcpy(&pDst->Timing.clockTickH0, &pSrc->Timing.clockTickH0, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.clockTickH1);
   memcpy(&pDst->Timing.clockTickH1, &pSrc->Timing.clockTickH1, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.tFinal);
   memcpy(&pDst->Timing.tFinal, &pSrc->Timing.tFinal, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.offsetTimesArray);
   memcpy(&pDst->Timing.offsetTimesArray, &pSrc->Timing.offsetTimesArray, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.perTaskSampleHitsArray);
   memcpy(&pDst->Timing.perTaskSampleHitsArray, &pSrc->Timing.perTaskSampleHitsArray, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.sampleHitArray);
   memcpy(&pDst->Timing.sampleHitArray, &pSrc->Timing.sampleHitArray, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.sampleTimesArray);
   memcpy(&pDst->Timing.sampleTimesArray, &pSrc->Timing.sampleTimesArray, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.sampleTimeTaskIDArray);
   memcpy(&pDst->Timing.sampleTimeTaskIDArray, &pSrc->Timing.sampleTimeTaskIDArray, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.simTimeStep);
   memcpy(&pDst->Timing.simTimeStep, &pSrc->Timing.simTimeStep, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.tStart);
   memcpy(&pDst->Timing.tStart, &pSrc->Timing.tStart, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.stepSize);
   memcpy(&pDst->Timing.stepSize, &pSrc->Timing.stepSize, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.stepSize0);
   memcpy(&pDst->Timing.stepSize0, &pSrc->Timing.stepSize0, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.stepSize1);
   memcpy(&pDst->Timing.stepSize1, &pSrc->Timing.stepSize1, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.stopRequestedFlag);
   memcpy(&pDst->Timing.stopRequestedFlag, &pSrc->Timing.stopRequestedFlag, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.tArray);
   memcpy(&pDst->Timing.tArray, &pSrc->Timing.tArray, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->Timing.timeOfLastOutput);
   memcpy(&pDst->Timing.timeOfLastOutput, &pSrc->Timing.timeOfLastOutput, eltSize);
   size += eltSize;

   return size;
}

/**
 * This function is generated by RT-LAB during model compilation (at 'generation' step).
 * This function copies data from a raw buffer (src) 
 * to an RT_MODEL structure(dst), ignoring pointers.
 * Note that ingData must not be copied since it contains pointers.
 */
int OpalSnapshot_Copy_ModelData(void * src, void * dst) {
   RT_MODEL	tmpBuffer;
   RT_MODEL * pSrc = &tmpBuffer;
   RT_MODEL * pDst = (RT_MODEL *)dst;
   int ModelDataSize = sizeof(tmpBuffer.ModelData);
   int size = 0, eltSize = 0;

   memcpy(&tmpBuffer.ModelData, src, ModelDataSize);

   eltSize = sizeof(pSrc->ModelData.CTOutputIncnstWithState);
   memcpy(&pDst->ModelData.CTOutputIncnstWithState, &pSrc->ModelData.CTOutputIncnstWithState, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->ModelData.derivCacheNeedsReset);
   memcpy(&pDst->ModelData.derivCacheNeedsReset, &pSrc->ModelData.derivCacheNeedsReset, eltSize);
   size += eltSize;

   eltSize = sizeof(pSrc->ModelData.zCCacheNeedsReset);
   memcpy(&pDst->ModelData.zCCacheNeedsReset, &pSrc->ModelData.zCCacheNeedsReset, eltSize);
   size += eltSize;

   return size;
}

